### ISSUE TITLE
Moving Images into the root of the repo

### ISSUE THREAD

**Issue by svx** [plone/documentation-roboshots#1]
Question @polyester and @gforcada would it be OK to move all the images out of the sub directory into the / (root aka top dir) of the repository ?
This would make auto git cloning way easier during testing and building

**Comment by polyester** [comment]
Not a problem at all, I will adapt the 'how to create the shots' readme in Products.CMFPlone

**Comment by svx** [comment]
@polyester thanks ! 

The other thing what we still have to figure out, is how to create a pinned/stable set of the images for certain versions, maybe with a tag and a branch ?

**Comment by gforcada** [comment]
Not sure why I should be involved on deciding where images go, but yes: -)

**Comment by polyester** [comment]
There's now a tagged branch, to check just that one out (for deployment) use
git clone -b 'v5.1rc1' --single-branch --depth 1 https://github.com/plone/documentation-roboshots
